<a href="https://colab.research.google.com/github/lucasfreire01/chicago_crime/blob/main/split_data_chicago.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import pandas as pd

In [15]:
dataset = pd.read_csv('/content/Chicago Total Crimes 2001 - 2023.csv')

<ipython-input-15-5b2a61f1eb4e>:1: DtypeWarning: Columns (7,8) have mixed types. Specify dtype option on import or set low_memory=False.
  dataset = pd.read_csv('/content/Chicago Total Crimes 2001 - 2023.csv')

In [16]:
dataset.columns

Index(['Case Number', 'Date', 'Block', 'IUCR', 'Primary Type', 'Description',
       'Location Description', 'Arrest', 'Domestic', 'Beat', 'District',
       'Ward', 'Community Area', 'FBI Code', 'X Coordinate', 'Y Coordinate',
       'Latitude', 'Longitude', 'Location'],
      dtype='object')

In [17]:
dataset

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Latitude,Longitude,Location
0,JC213529,09/01/2018 12:01:00 AM,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,631.0,6.0,8.0,44.0,06,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN
1,JC212333,05/01/2016 12:25:00 AM,055XX S ROCKWELL ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,824.0,8.0,15.0,63.0,11,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN
2,JB373031,07/31/2018 01:30:00 PM,009XX E HYDE PARK BLVD,2024,NARCOTICS,POSS: HEROIN(WHITE),STREET,True,False,233.0,2.0,5.0,41.0,18,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN
3,JC209972,12/19/2018 04:30:00 PM,056XX W WELLINGTON AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,2514.0,25.0,31.0,19.0,14,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN
4,JC212744,02/02/2015 10:00:00 AM,069XX W ARCHER AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER,False,False,811.0,8.0,23.0,56.0,11,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4345294,HL540559,08/10/2005 02:30:00 PM,052XX S CORNELL AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,False,2132.0,2.0,4.0,41.0,06,1.188049e+06,1.870822e+06,41.800619,-87.585887,"(41.80061868, -87.585887262)"
4345295,HL540581,08/10/2005 12:00:00 AM,024XX S KOSTNER AVE,0810,THEFT,OVER $500,RESIDENCE,False,False,1013.0,10.0,22.0,29.0,06,1.147441e+06,1.887556e+06,41.847412,-87.734383,"(41.847411621, -87.734383098)"
4345296,HL540577,08/10/2005 03:00:00 PM,049XX W CONGRESS PKWY,0820,THEFT,$500 AND UNDER,STREET,False,False,1533.0,15.0,24.0,25.0,06,1.143701e+06,1.897232e+06,41.874035,-87.747867,"(41.874034597, -87.74786694)"
4345297,HL540598,08/10/2005 12:00:00 AM,030XX S HALSTED ST,1310,CRIMINAL DAMAGE,TO PROPERTY,RESTAURANT,False,False,923.0,9.0,11.0,60.0,14,1.171462e+06,1.884752e+06,41.839224,-87.646308,"(41.839223645, -87.64630829)"
4345298,HL536908,07/21/2005 04:50:00 P,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
#trated the date column split in day, month and year
dataset['Date'] = pd.to_datetime(dataset['Date'])
dataset['Day'] = dataset['Date'].dt.day
dataset['Month'] = dataset['Date'].dt.month
dataset['Year'] = dataset['Date'].dt.year

In [21]:
dataset

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Latitude,Longitude,Location,Day,Month,Year
0,JC213529,2018-09-01 00:01:00,082XX S INGLESIDE AVE,0810,THEFT,OVER $500,RESIDENCE,False,True,631.0,...,44.0,06,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN,1,9,2018
1,JC212333,2016-05-01 00:25:00,055XX S ROCKWELL ST,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,NaN,False,False,824.0,...,63.0,11,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN,1,5,2016
2,JB373031,2018-07-31 13:30:00,009XX E HYDE PARK BLVD,2024,NARCOTICS,POSS: HEROIN(WHITE),STREET,True,False,233.0,...,41.0,18,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN,31,7,2018
3,JC209972,2018-12-19 16:30:00,056XX W WELLINGTON AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,2514.0,...,19.0,14,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN,19,12,2018
4,JC212744,2015-02-02 10:00:00,069XX W ARCHER AVE,1153,DECEPTIVE PRACTICE,FINANCIAL IDENTITY THEFT OVER $ 300,OTHER,False,False,811.0,...,56.0,11,-2.147484e+09,-2.147484e+09,NaN,NaN,NaN,2,2,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4345294,HL540559,2005-08-10 14:30:00,052XX S CORNELL AVE,0820,THEFT,$500 AND UNDER,RESIDENCE,False,False,2132.0,...,41.0,06,1.188049e+06,1.870822e+06,41.800619,-87.585887,"(41.80061868, -87.585887262)",10,8,2005
4345295,HL540581,2005-08-10 00:00:00,024XX S KOSTNER AVE,0810,THEFT,OVER $500,RESIDENCE,False,False,1013.0,...,29.0,06,1.147441e+06,1.887556e+06,41.847412,-87.734383,"(41.847411621, -87.734383098)",10,8,2005
4345296,HL540577,2005-08-10 15:00:00,049XX W CONGRESS PKWY,0820,THEFT,$500 AND UNDER,STREET,False,False,1533.0,...,25.0,06,1.143701e+06,1.897232e+06,41.874035,-87.747867,"(41.874034597, -87.74786694)",10,8,2005
4345297,HL540598,2005-08-10 00:00:00,030XX S HALSTED ST,1310,CRIMINAL DAMAGE,TO PROPERTY,RESTAURANT,False,False,923.0,...,60.0,14,1.171462e+06,1.884752e+06,41.839224,-87.646308,"(41.839223645, -87.64630829)",10,8,2005
4345298,HL536908,2005-07-21 16:50:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21,7,2005

In [29]:
#The distribuation of year column
dataset['Year'].value_counts()

2002    486681
2001    485043
2003    475652
2004    468677
2016    269813
2017    269095
2018    268813
2005    266205
2019    261282
2022    238740
2015    218596
2020    212175
2021    208763
2023    147398
2008     12371
2009     11729
2006      8362
2007      6994
2014      6768
2010      5679
2012      5534
2013      5503
2011      5426
Name: Year, dtype: int64

In [30]:
#In the dataset the date values is messy so we organieze it based in the month and year
dataset = dataset.sort_values(by=['Year', 'Month'])

In [26]:
dataset

,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,...,Community Area,FBI Code,X Coordinate,Y Coordinate,Latitude,Longitude,Location,Day,Month,Year
2629487,G698410,2001-01-01 00:01:00,049XX S DR MARTN LUTHR KING JR DR,1130,DECEPTIVE PRACTICE,FRAUD OR CONFIDENCE GAME,COMMERCIAL / BUSINESS OFFICE,True,False,224.0,...,-128.0,11,1179651.0,1872480.0,41.805365,-87.616634,"(41.805364641, -87.616634399)",1,1,2001
2630759,G697906,2001-01-27 16:00:00,020XX N LAMON AV,0810,THEFT,OVER $500,RESIDENCE,True,False,2522.0,...,-128.0,06,1143330.0,1913027.0,41.917385,-87.748834,"(41.917384835, -87.74883402)",27,1,2001
2637251,G711738,2001-01-15 18:00:00,049XX W BYRON ST,2820,OTHER OFFENSE,TELEPHONE THREAT,RESIDENCE,False,True,1634.0,...,-128.0,26,1142847.0,1925428.0,41.951423,-87.750299,"(41.951423407, -87.750298745)",15,1,2001
2637593,G696182,2001-01-19 13:27:00,043XX S STATE ST,2027,NARCOTICS,POSS: CRACK,STREET,True,False,221.0,...,-128.0,18,1176951.0,1876477.0,41.816394,-87.626416,"(41.816394124, -87.626416241)",19,1,2001
2637664,G712278,2001-01-01 00:01:00,027XX S HAMLIN AV,1562,SEX OFFENSE,AGG CRIMINAL SEXUAL ABUSE,RESIDENCE,False,False,1031.0,...,-128.0,17,1151439.0,1885627.0,41.842041,-87.719761,"(41.84204075, -87.719760856)",1,1,2001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229283,JG356536,2023-07-25 23:00:00,007XX S CLARK ST,1320,CRIMINAL DAMAGE,TO VEHICLE,VEHICLE NON-COMMERCIAL,False,False,123.0,...,32.0,14,1175633.0,1897092.0,41.872993,-87.630632,"(41.872992906, -87.63063219)",25,7,2023
266240,JG357608,2023-07-27 00:18:00,071XX S CORNELL AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,324.0,...,43.0,08B,1188470.0,1857976.0,41.765358,-87.584753,"(41.765358204, -87.58475348)",27,7,2023
261928,JG360585,2023-07-28 20:00:00,014XX W HOWARD ST,0810,THEFT,OVER $500,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,2422.0,...,1.0,06,1165303.0,1950303.0,42.019232,-87.667040,"(42.019232277, -87.66703966)",28,7,2023
262086,JG359155,2023-07-27 15:57:00,032XX W OGDEN AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,1022.0,...,29.0,07,1155111.0,1891369.0,41.857725,-87.706132,"(41.857724686, -87.70613173)",27,7,2023
263159,JG358013,2023-07-27 11:00:00,032XX S PRAIRIE AVE,0460,BATTERY,SIMPLE,APARTMENT,False,False,211.0,...,35.0,08B,1178466.0,1883520.0,41.835686,-87.620645,"(41.835686337, -87.620644613)",27,7,2023

In [28]:
#As this dataset is so big we split in train and test, the train dataset have 60% of original dataset and test with 40% of original dataset
split_ratio = 0.6
split_idx = int(len(dataset) * split_ratio)

train = dataset[:split_idx]
test = dataset[split_idx:]

train.to_csv('train.csv', index=False)
test.to_csv('test.csv', index=False)